openapi: 3.0.0
info:
    title: Album Management
    description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
    version: 0.1.9
servers:
    - url: http://localhost:8080/
      description: Localhost

    #######################___________Add Components___________#######################
components:
    securitySchemes:
        BearerAuth:
            type: http
            scheme: bearer
            bearerFormat: JWT
    #######################___________Authorization___________#######################
paths:
    /login:
        post:
            tags:
                - Authorization
            summary: Login to the Album Management
            description:
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            required:
                                - username
                                - password
                            properties:
                                username:
                                    type: string
                                password:
                                    type: string
            responses:
                '200': # Login successful
                    description: Login successful!
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                '500':
                    description: Login Failed!
                default:
                    description: Unexpected error
    /register:
        post:
            tags:
                - Authorization
            summary: Register
            description:
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            required:
                                - username
                                - password
                                - name
                                - email
                            properties:
                                username:
                                    type: string
                                password:
                                    type: string
                                email:
                                    type: string
                                name:
                                    type: string
            responses:
                '200': # Login successful
                    description: Login successful!
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                '500':
                    description: Register Failed!
                default:
                    description: Unexpected error
    /register/verify:
        post:
            tags:
                - Authorization
            summary: Register - Verify
            description:
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            required:
                                - username
                                - activeCode
                            properties:
                                username:
                                    type: string
                                activeCode:
                                    type: string
            responses:
                '200': # Verify successful
                    description: Verify successful!
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                '500':
                    description: Verify Failed!
                default:
                    description: Unexpected error
    /user/show-info:
        get:
            security:
                - BearerAuth: []
            tags:
                - Users
            summary: Show user info
            description:
            responses:
                '200': # Verify successful
                    description: Verify successful!
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                '500':
                    description: Verify Failed!
                default:
                    description: Unexpected error
    /user/forgot-password:
        patch:
            tags:
                - Users
            summary: Forgot - password
            description:
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            required:
                                - username
                            properties:
                                username:
                                    type: string
            responses:
                '200': # Verify successful
                    description: Verify successful!
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                '500':
                    description: Verify Failed!
                default:
                    description: Unexpected error
    /user/forgot-password/verify:
        patch:
            tags:
                - Users
            summary: Forgot - password Verify
            description:
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            required:
                                - username
                                - activeCode
                            properties:
                                username:
                                    type: string
                                activeCode:
                                    type: string
            responses:
                '200': # Forgot password successful
                    description: Forgot password successful
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                '500':
                    description: Forgot password Failed!
                default:
                    description: Unexpected error

    /user/change-password:
        patch:
            security:
                - BearerAuth: []
            tags:
                - Users
            summary: Change password
            description:
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            required:
                                - password
                                - newpassword
                            properties:
                                password:
                                    type: string
                                newpassword:
                                    type: string
            responses:
                '200': # Change password successful
                    description: Change password successful
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                '500':
                    description: Change password Failed!
                default:
                    description: Unexpected error
    /user/change-info:
        patch:
            security:
                - BearerAuth: []
            tags:
                - Users
            summary: Change info
            description: name, email, dob, gender.
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            required:
                            properties:
            responses:
                '200': # Change info successful
                    description: Change info successful
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                '500':
                    description: Change info Failed!
                default:
                    description: Unexpected error

    #######################___________Album___________#######################
    /album/create:
        post:
            security:
                - BearerAuth: []
            tags:
                - Album
            summary: Create album
            description:
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            required:
                                - nameAlbum
                            properties:
                                nameAlbum:
                                    type: string
                                desciption:
                                    type: string
            responses:
                '200': # Create album successful
                    description: Create album successful
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                '500':
                    description: Create album Failed!
                default:
                    description: Unexpected error
    /album/show:
        get:
            security:
                - BearerAuth: []
            tags:
                - Album
            summary: Show Album
            description:
            responses:
                '200': # Show album successful
                    description: Show album
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                '500':
                    description: Show album Failed!
                default:
                    description: Unexpected error
    /album/update:
        patch:
            security:
                - BearerAuth: []
            tags:
                - Album
            summary: Update album
            description:
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            required:
                                - albumID
                            properties:
                                albumID:
                                    type: string
                                description:
                                    type: string
            responses:
                '200': # Update album successful
                    description: Update album successful
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                '500':
                    description: Update album Failed!
                default:
                    description: Unexpected error
    /album/delete:
        delete:
            security:
                - BearerAuth: []
            tags:
                - Album
            summary: Delete album
            description:
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            required:
                                - albumID
                            properties:
                                albumID:
                                    type: string
            responses:
                '200': # Delete album successful
                    description: Delete album successful
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                '500':
                    description: Delete album Failed!
                default:
                    description: Unexpected error

    #######################___________userAlbum___________#######################
    /album/invite:
        post:
            security:
                - BearerAuth: []
            tags:
                - User Album
            summary: Invite user to album
            description:
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            required:
                                - invitee
                                - albumID
                            properties:
                                invitee:
                                    type: string
                                albumID:
                                    type: string
            responses:
                '200': # Invite successful
                    description: Invite successful
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                '500':
                    description: Invite Failed!
                default:
                    description: Unexpected error
    /album/remove:
        delete:
            security:
                - BearerAuth: []
            tags:
                - User Album
            summary: Remove user from album
            description:
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            required:
                                - invitee
                                - albumID
                            properties:
                                invitee:
                                    type: string
                                albumID:
                                    type: string
            responses:
                '200': # Remove successful
                    description: Remove successful
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                '500':
                    description: Remove Failed!
                default:
                    description: Unexpected error

    #######################___________Photo___________#######################
    /photo/upload:
        post:
            security:
                - BearerAuth: []
            tags:
                - Photo
            summary: Upload photo
            requestBody:
                content:
                    multipart/form-data:
                        schema:
                            type: object
                            properties:
                                image:
                                    type: string
                                    format: binary

                description: The file to upload.
            responses:
                '200': # Upload successful
                    description: Upload successful
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                '500':
                    description: Upload Failed!
                default:
                    description: Unexpected error
    /photo/delete:
        delete:
            security:
                - BearerAuth: []
            tags:
                - Photo
            summary: Delete photo
            description:
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            required:
                                - photoID
                            properties:
                                photoID:
                                    type: string
            responses:
                '200': # Delete photo successful
                    description: Delete photo successful
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                '500':
                    description: Delete photo Failed!
                default:
                    description: Unexpected error
    /photo/addToAlbum:
        patch:
            security:
                - BearerAuth: []
            tags:
                - Photo
            summary: Add photo to album
            description:
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            required:
                                - photoID
                                - albumID
                            properties:
                                photoID:
                                    type: string
                                albumID:
                                    type: string
            responses:
                '200': # Add photo to album successful
                    description: Add photo to album successful
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                '500':
                    description: Add photo to album Failed!
                default:
                    description: Unexpected error
